name: Flutter_Test_Build

on:
  push:
    branches: [main]

jobs:
  build_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "microsoft"
          java-package: "jdk"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: "stable"

      - name: Restore packages
        run: flutter pub get

      - name: Build Android App Bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: flutter build appbundle --build-number ${{ steps.buildnumber.outputs.build_number }} --build-name ${{ steps.tag.outputs.new_version }}

      - name: Publish Android Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/release.aab

      #This is based on the API Service once configured in the Google Play Console
      # - name: Deploy to Alpha
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJson: service_account.json
      #     packageName: com.app.mittarv
      #     releaseFile: build/app/outputs/bundle/release/app-release.aab
      #     releaseName: ${{ secrets.GITHUB_TOKEN }}
      #     track: alpha
      #     status: completed
      #debugSymbols:
